# CMake generated Testfile for 
# Source directory: /home/mahi/labs/NFIQ2/NFIQ2/OpenCV/modules
# Build directory: /home/mahi/labs/NFIQ2/NFIQ2/libOpenCV/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(androidcamera/.androidcamera)
SUBDIRS(calib3d/.calib3d)
SUBDIRS(contrib/.contrib)
SUBDIRS(core/.core)
SUBDIRS(dynamicuda/.dynamicuda)
SUBDIRS(features2d/.features2d)
SUBDIRS(flann/.flann)
SUBDIRS(gpu/.gpu)
SUBDIRS(highgui/.highgui)
SUBDIRS(imgproc/.imgproc)
SUBDIRS(java/.java)
SUBDIRS(legacy/.legacy)
SUBDIRS(ml/.ml)
SUBDIRS(nonfree/.nonfree)
SUBDIRS(objdetect/.objdetect)
SUBDIRS(ocl/.ocl)
SUBDIRS(photo/.photo)
SUBDIRS(python/.python)
SUBDIRS(stitching/.stitching)
SUBDIRS(superres/.superres)
SUBDIRS(ts/.ts)
SUBDIRS(video/.video)
SUBDIRS(videostab/.videostab)
SUBDIRS(viz/.viz)
SUBDIRS(world/.world)
SUBDIRS(core)
SUBDIRS(flann)
SUBDIRS(imgproc)
SUBDIRS(highgui)
SUBDIRS(features2d)
SUBDIRS(calib3d)
SUBDIRS(ml)
SUBDIRS(video)
SUBDIRS(legacy)
SUBDIRS(objdetect)
SUBDIRS(photo)
SUBDIRS(gpu)
SUBDIRS(ocl)
SUBDIRS(nonfree)
SUBDIRS(contrib)
SUBDIRS(stitching)
SUBDIRS(superres)
SUBDIRS(ts)
SUBDIRS(videostab)
